development:
  adapter: postgresql
  database: <%= ENV['PG_DATABASE'] || 'wishme-backend_development' %>
  username: <%= ENV['PG_USERNAME'] || 'wishme-backend' %>
  password: <%= ENV['PG_PASSWORD'] || 'wishme-backend' %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: <%= ENV['PG_DATABASE'] || 'wishme-backend_production' %>
  username: <%= ENV['PG_USERNAME'] || 'wishme-backend' %>
  password: <%= ENV['PG_PASSWORD'] || 'wishme-backend' %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  pool: <%= ENV['PG_POOL'] || 100 %>
  timeout: 5000